title: "ê¹€ë¯¼ì„± ë¸”ë¡œê·¸" # name of the site
author: "Castle" # name of site's author
email: "yssj2049@gmail.com" # email of site's author
url: "https://miseongkimdev.github.io" # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: "<p>ğŸ° Castle Kim Tech Blog âœ</p>
<p>ê³µë¶€í•œ ê²ƒì„ ê¸°ë¡í•˜ëŠ” ê³µê°„ì…ë‹ˆë‹¤.</p>
<p>ë¸”ë¡œê·¸ ì£¼ë„ ê°œë°œì„ ì‹¤ì²œ ì¤‘ì…ë‹ˆë‹¤.</p>
<p>ê¸€ ë‚´ìš©ì—ë§Œ ì§‘ì¤‘í•  ìˆ˜ ìˆë„ë¡ CSSë¥¼ ìµœì†Œí™” í•˜ì˜€ìŠµë‹ˆë‹¤.</p>
<p>ê¸°ìˆ ì ì¸ í”¼ë“œë°±ê³¼ í† ë¡ ì€ ì–¸ì œë‚˜ í™˜ì˜í•©ë‹ˆë‹¤.</p>"
# description of the site (multiple lines allowed)


permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y.%m.%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

highlighter: rouge